### ISSUE TITLE
Feature: Login

### ISSUE THREAD

**Issue by jferragut** [jferragut/starwars-api#2]
We need a login system for the site. Users should be able to Login.

**Tasks:**
- [ ] Design login
- [ ] Code Login View
- [ ] Add view to Router
- [ ] Make actions in store

**Acceptance Criteria:**
- [ ] Should be able to click login from menu
- [ ] Should see "Login" if logged out, and "Logout" if logged in
- [ ] Should see Profile and Favorites only when logged in
- [ ] Should be able to log in with a valid email and password
